plugins {
    id 'com.android.application'
}

android {
    namespace 'net.nerdhalla.sharla'
    compileSdk 35

    defaultConfig {
        applicationId 'net.nerdhalla.sharla'
        minSdk 26
        targetSdk 35
        versionCode 234
        versionName '2.3.4'
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
}
